CREATE TABLE POI (
   id BIGINT AUTO_INCREMENT NOT NULL,
   latitud DECIMAL NOT NULL,
   longitud DECIMAL NOT NULL,
   nombre VARCHAR(100) NOT NULL,
   descripcion VARCHAR(255) NULL default NULL,
   categoria VARCHAR(100) NOT NULL,
   PRIMARY KEY (id)
);

create table itinerario (
       id bigint generated by default as identity,
        descripcion varchar(255),
        nombre varchar(255),
        primary key (id)
    );

    create table itinerario_lista_de_pois (
       itinerario_id bigint not null,
        lista_de_pois_id bigint not null
    );

    create table submapa (
       id bigint generated by default as identity,
        nombre varchar(255),
        primary key (id)
    ) ;

    create table submapa_pois (
       submapa_id bigint not null,
        pois_id bigint not null
    );

    alter table itinerario_lista_de_pois
       drop constraint if exists UK_c7mdautbs2jyic60ce47hu1vf;

    alter table itinerario_lista_de_pois
       add constraint UK_c7mdautbs2jyic60ce47hu1vf unique (lista_de_pois_id);

    alter table submapa_pois
       drop constraint if exists UK_1ut8gi1l8mop3tug0mr0j54o5;

    alter table submapa_pois
       add constraint UK_1ut8gi1l8mop3tug0mr0j54o5 unique (pois_id);

    alter table itinerario_lista_de_pois
       add constraint FKfu82tms41yqs1aellwsyg24hu
       foreign key (lista_de_pois_id)
       references poi;

    alter table itinerario_lista_de_pois
       add constraint FK5bdsrud5u8byj1jx3iiufyr0f
       foreign key (itinerario_id)
       references itinerario;

    alter table submapa_pois
       add constraint FK1bvsujqctguwnebsq2meu68an
       foreign key (pois_id)
       references poi;


    alter table submapa_pois
       add constraint FKbq8x70lywk78ennkwiru0chyp
       foreign key (submapa_id)
       references submapa;
       alter table itinerario_lista_de_pois
              drop constraint if exists UK_c7mdautbs2jyic60ce47hu1vf;


           alter table itinerario_lista_de_pois
              add constraint UK_c7mdautbs2jyic60ce47hu1vf unique (lista_de_pois_id);

           alter table submapa_pois
              drop constraint if exists UK_1ut8gi1l8mop3tug0mr0j54o5;

           alter table submapa_pois
              add constraint UK_1ut8gi1l8mop3tug0mr0j54o5 unique (pois_id);

INSERT INTO POI(latitud, longitud, nombre, descripcion, categoria)
VALUES(-34.58791299400182,-58.423084840222,'Rapa nui','Una rica heladeria','heladeria');
INSERT INTO POI(latitud, longitud, nombre, descripcion, categoria)
VALUES(-34.58958675108932,-58.42795175118532,'Freddo','Otra heladeria','heladeria');
INSERT INTO POI(latitud, longitud, nombre, descripcion, categoria)
VALUES(-34.58428917744298, -58.43766774433044,'Buenos aires verde','Un restaurant verde','restaurant');
